In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/RodrigoARivasG/etl-data-pipeline2509642022/refs/heads/main/data/raw/E_inventario.csv"

df = pd.read_csv(url)

df.head()

  id_inventario id_bodega            item cantidad costo_unitario
0       INV5000    BOD103     Producto 45      359         192.81
1       INV5001    BOD111      Producto 2      419         153.48
2       INV5002    BOD999   Producto 120        58         104.91
3       INV5003    BOD100     Producto 42      422       $ 138.66
4       INV5004    BOD112     Producto 79      257            NaN

In [6]:
inventario = df.copy()

# Normalizar columnas
inventario.columns = inventario.columns.str.strip().str.lower()

# Limpiar strings
for col in inventario.select_dtypes(include="object").columns:
    inventario[col] = inventario[col].astype(str).str.strip()

# Quitar "uds"
for col in inventario.select_dtypes(include="object").columns:
    inventario[col] = inventario[col].str.replace(r'\buds\b', '', regex=True, case=False).str.strip()

inventario['cantidad'] = pd.to_numeric(inventario['cantidad'], errors='coerce').astype('Int64')

inventario['costo_unitario'] = (
    inventario['costo_unitario']
    .astype(str)
    .str.replace('$', '', regex=False)
    .str.replace(',', '', regex=False)
    .str.strip()
)

inventario['costo_unitario'] = pd.to_numeric(inventario['costo_unitario'], errors='coerce')

# Convertir vacíos a NA
inventario = inventario.replace(r'^\s*$', pd.NA, regex=True)
inventario = inventario.replace("nan", pd.NA)

# Cantidad
if 'cantidad' in inventario.columns:
    inventario['cantidad'] = pd.to_numeric(inventario['cantidad'], errors='coerce')

# Precio
if 'precio' in inventario.columns:
    inventario['precio'] = pd.to_numeric(inventario['precio'], errors='coerce')

# Producto
if 'producto' in inventario.columns:
    inventario['producto'] = inventario['producto'].astype("string").str.title()

# Bodega
if 'bodega' in inventario.columns:
    inventario['bodega'] = inventario['bodega'].astype("string").str.title()

# Eliminar duplicados
inventario = inventario.drop_duplicates()

In [14]:
cond_validos = pd.Series([True] * len(inventario))

if 'producto' in inventario.columns:
    cond_validos &= inventario['producto'].notna()
    cond_validos &= (inventario['producto'] != 'Error')
    cond_validos &= (~inventario['producto'].str.startswith('Text_', na=False))

if 'bodega' in inventario.columns:
    cond_validos &= inventario['bodega'].notna()
    cond_validos &= (inventario['bodega'] != 'Error')
    cond_validos &= (~inventario['bodega'].str.startswith('Text_', na=False))

if 'cantidad' in inventario.columns:
    cond_validos &= inventario['cantidad'].notna()

if 'precio' in inventario.columns:
    cond_validos &= inventario['precio'].notna()

if 'costo_unitario' in inventario.columns:
    cond_validos &= inventario['costo_unitario'].notna()

validos = inventario[cond_validos].copy()
rechazados = inventario[~cond_validos].copy()

In [15]:
def motivo(row):
    motivos = []

    if 'producto' in row:
        if pd.isna(row['producto']):
            motivos.append("producto_vacio")
        elif row['producto'] == 'Error':
            motivos.append("producto_error")
        elif isinstance(row['producto'], str) and row['producto'].startswith('Text_'):
            motivos.append("producto_text_pattern")

    if 'bodega' in row:
        if pd.isna(row['bodega']):
            motivos.append("bodega_vacia")
        elif row['bodega'] == 'Error':
            motivos.append("bodega_error")
        elif isinstance(row['bodega'], str) and row['bodega'].startswith('Text_'):
            motivos.append("bodega_text_pattern")

    if 'cantidad' in row and pd.isna(row['cantidad']):
        motivos.append("cantidad_invalida")

    if 'precio' in row and pd.isna(row['precio']):
        motivos.append("precio_invalido")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [16]:
validos.to_csv("inventario_curated.csv", index=False)
rechazados.to_csv("inventario_rejects.csv", index=False)

In [10]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_rivas:ks9EQNpC43n64cYY21G6e2BUn85omaRa@dpg-d6qu610gjchc73en58b0-a.oregon-postgres.render.com/etl_seguros_h814"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 51.3 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [18]:
validos.to_sql(
    'inventario_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'inventario_rejects',
    engine,
    if_exists='append',
    index=False
)

21

In [19]:
pd.read_sql(
    "SELECT * FROM inventario_curated LIMIT 10",
    engine
)

  id_inventario id_bodega          item  cantidad  costo_unitario
0       INV5000    BOD103   Producto 45       359          192.81
1       INV5001    BOD111    Producto 2       419          153.48
2       INV5002    BOD999  Producto 120        58          104.91
3       INV5003    BOD100   Producto 42       422          138.66
4       INV5005      None   Producto 57       488          228.60
5       INV5006    BOD111   Producto 88       436          333.93
6       INV5007    BOD111   Producto 64       401          167.73
7       INV5008    BOD106   Producto 98       173          307.79
8       INV5010    BOD102   Producto 18        53           93.98
9       INV5012    BOD117  Producto 111       330          288.22